name: 🔁 API Regression Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress regression suite
        run: npx cypress run --record --key b0043287-11b9-4dda-8131-121eab081a70
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}